name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: ankane/pgvector:latest
        env:
          POSTGRES_DB: agent_team_test
          POSTGRES_USER: agent_user
          POSTGRES_PASSWORD: agent_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Initialize test database
        run: |
          psql -h localhost -U agent_user -d agent_team_test -f infra/database/schema.sql
        env:
          PGPASSWORD: agent_password

      - name: Run tests
        run: |
          pytest --cov=agents
        env:
          DATABASE_URL: postgresql://agent_user:agent_password@localhost:5432/agent_team_test
          REDIS_URL: redis://localhost:6379/0
