# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f agents/requirements.txt ]; then pip install -r agents/requirements.txt; fi
          if [ -f agents/requirements-dev.txt ]; then pip install -r agents/requirements-dev.txt; fi
      - name: Lint with ruff
        run: |
          if [ -d agents ]; then
            pip install ruff
            ruff check agents
          fi
      - name: Test with pytest
        run: |
          if [ -d agents ]; then
            pip install pytest pytest-cov
            pytest agents
          fi

  typescript-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: |
          if [ -d dashboard ]; then
            cd dashboard
            npm ci
          fi
      - name: Lint
        run: |
          if [ -d dashboard ]; then
            cd dashboard
            npm run lint
          fi
      - name: Build
        run: |
          if [ -d dashboard ]; then
            cd dashboard
            npm run build
          fi
      - name: Test
        run: |
          if [ -d dashboard ]; then
            cd dashboard
            npm test
          fi
