name: TypeScript CI

on:
  push:
    branches: [main]
    paths:
      - "dashboard/**"
      - ".github/workflows/typescript-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "dashboard/**"
      - ".github/workflows/typescript-ci.yml"

jobs:
  lint:
    name: Lint and format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dashboard
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "dashboard/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Lint with ESLint
        run: npm run lint
      - name: Check TypeScript
        run: npm run type-check
      - name: Check formatting with Prettier
        run: npm run prettier:check

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        working-directory: dashboard
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "dashboard/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --coverage
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./dashboard/coverage
          fail_ci_if_error: true

  build:
    name: Build frontend
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: dashboard
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "dashboard/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dashboard/.next
          retention-days: 7
