"""add_created_by_to_project

Revision ID: e0ab3e5246dc
Revises: d864f9db2335
Create Date: 2025-05-18 04:54:04.203923

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = "e0ab3e5246dc"
down_revision: Union[str, None] = "d864f9db2335"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("created_by", sa.UUID(as_uuid=True), nullable=True)
    )
    op.create_foreign_key(
        "fk_projects_created_by_agents",
        "projects",
        "agents",
        ["created_by"],
        ["agent_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_projects_created_by_agents", "projects", type_="foreignkey")
    op.drop_column("projects", "created_by")
    # ### end Alembic commands ###
